
// This file was generated by BetterInputActionsSourceGenerator.cs!!!
// DONT CHANGE THIS FILE MANUALLY!!!

using System;
using System.Collections.Generic;
using DatastoresDX.Runtime;
using DatastoresDX.Runtime.DataCollections;
using UnityEngine.InputSystem;
            
namespace BetterInputSystem.Runtime
{
    public partial class BetterInputActions
    {
        public List<BetterActionMap> BetterActionMaps { get; } = new();
        public Action OnAnyInputActionEnabledChanged;

        public DebugActionMap DebugActionMap { get; private set; }

        public Map Map { get; private set; }

        private void GeneratedInitialize()
        {
            Dictionary<string, BetterInputActionsData> actionsData = new();
            foreach (DataCollectionElement element in GetAllElements())
            {
                BetterInputActionsData actionMap = element as BetterInputActionsData;
                actionsData.Add(actionMap.DisplayName.Replace(" ", ""), actionMap);
            }

            DebugActionMap = new DebugActionMap(m_debugActionMap);
            DebugActionMap.Enable(true);
            DebugActionMap.OnEnableChanged += () => { OnAnyInputActionEnabledChanged?.Invoke(); };

            Map = new Map(actionsData[""]);
            BetterActionMaps.Add(Map);

            foreach (BetterActionMap betterActionMap in BetterActionMaps)
            {
                betterActionMap.Enable(false);
                betterActionMap.OnEnableChanged += () => { OnAnyInputActionEnabledChanged?.Invoke(); };
            }
        }
    }

    public class DebugActionMap : BetterActionMap
    {
        public DebugActionMap(InputActionMap actionMap)
        {
            ActionMap = actionMap;
            ElementId = Uid.Invalid;
        }
    }

    public class Map : BetterActionMap
    {
        public BetterInputActionsData BetterInputActionsData { get; }
        public Map(BetterInputActionsData actionsData)
        {
            BetterInputActionsData = actionsData;
            ActionMap = actionsData.ActionMap;
            ElementId = actionsData.Id;
        }
    }
}